### PR TITLE
chore: improve linking

### PR DESCRIPTION
**Pull request by marcoscaceres**
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/page-visibility/pull/35.html" title="Last updated on Dec 14, 2017, 10:21 PM GMT (ae50e02)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/page-visibility/35/5cac75b...ae50e02.html" title="Last updated on Dec 14, 2017, 10:21 PM GMT (ae50e02)">Diff</a>

### CODE REVIEW

**Comment by siusin** [comment]
Thanks @marcoscaceres .

Added this proposal to the [agenda](https://docs.google.com/document/d/10dz_7QM5XCNsGeI63R864lF9gFqlqQD37B4q8Q46LMM/edit#) of the next call.

**Comment by marcoscaceres** [comment]
Note that this are only markup changes, not content changes, so shouldn't need additional discussion. Just needs a look over to make sure I didn't miss/break anything :)

**Comment by marcoscaceres** [comment]
Oh wait! sorry @siusin, I forgot that I had renamed the enum. I did this before TPAC, so had totally forgotten. 

This PR fixes all the linking issues and hopefully simplifies things significantly.

**Comment by siusin** [comment]
@marcoscaceres I got confused... is it possible to fix the ref problem without renaming the `VisibilityState` enum?

**Comment by marcoscaceres** [comment]
>  is it possible to fix the ref problem without renaming the VisibilityState enum?

It SHOULD be... but I didn't manage to do it with the time I had. Changing the enum name is not particularly harmful tho, as it's not something that is reflected in the web platform in any meaningful way.

**Comment by marcoscaceres** [comment]
Tried again... alas, no. Sorry. ReSpec's linker gets confused between the attribute and the enum name. As I mentioned, I'm working on a fix for all that, but won't land till early next year. I'd suggest going with the rename for now - it's a cheap fix, and once I fix ReSpec, we can always change the enum name back.

**Comment by marcoscaceres** [comment]
Note, [broken links](https://validator.w3.org/checklink?uri=https%3A%2F%2Fs3.amazonaws.com%2Fpr-preview%2Fw3c%2Fpage-visibility%2Fpull%2F35.html&hide_type=all&depth=&check=Check).

**Comment by toddreifsteck** [comment]
Unless this is blocking, we discussed that we would prefer to wait for the Respec update allowing the names to stay the same. Both Chrome and Edge dev teams pull IDL from the specs for various tests.

**Comment by marcoscaceres** [comment]
Sounds reasonable. I'll switch the enum back and if all goes to plan, I should have this fixed over xmas.

**Comment by marcoscaceres** [comment]
Ok, sooooo... I reverted and enum's name and I've fixed the cross linking 🎉 but ReSpec is still erroneously warning that `VisibilityState` is not defined (it is, and everything now links to it). Please ignore that warning, will fix that soon.   

This gets us 99% of the way there.

**Comment by igrigorik** [comment]
Awesome, thanks @marcoscaceres!

**Review by siusin — APPROVED** [review]

**Pull request merged**
