### PR TITLE
Add external hooks to now {visible,hidden} algorithms

### LINKED ISSUE #40: Provide a clear way to hook into "document becomes visible/hidden"
Quoted from @mounirlamouri 's request in http://lists.w3.org/Archives/Public/public-web-perf/2014Sep/0034.html, also see [screen-orientation #77](https://github.com/w3c/screen-orientation/issues/77).

> The specification has "now visible algorithm" and "now hidden algorithm"
> but misses extension points at the end of those algorithms. It would be
> great to add such extension points so other specifications could cleanly
> define behaviour when the document visibility state changes.

The ref section in the SO spec

> Whenever a document becomes visible per [PAGE-VISIBILITY], in other words after the [now visible algorithm](https://www.w3.org/TR/page-visibility/#dfn-now-visible-algorithm) is run, the user agent MUST run the following substeps...

### PR DESCRIPTION
**Pull request by yoavweiss**
Fixes #40

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/page-visibility/pull/47.html" title="Last updated on Jun 25, 2019, 7:24 PM UTC (048e2c5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/page-visibility/47/85ce304...048e2c5.html" title="Last updated on Jun 25, 2019, 7:24 PM UTC (048e2c5)">Diff</a>

### CODE REVIEW

**Comment by mounirlamouri** [comment]
Thanks @yoavweiss :)

**Comment by toddreifsteck** [comment]
First.. THANKS to Yoav for writing this first draft. Now.. read the following to understand why I haven't yet made progress. I'm curious on the thinking around these and how we landed on this PR.
@mounirlamouri 

This update seems to allow a synchronous hook. This does solve the request.. but.. I'm not certain it is the proper design on first glance without understanding the features we are adding it for. How are they implemented? Do we have a place in a spec intends to reference this hook to help us reason about whether this is a synchronous execution hook OR should be a hook to start our processing model OR should we triggered an enqueued task for other subscribers?

**Review by toddreifsteck — CHANGES_REQUESTED** [review]
Please reply to comments and tag me. :-)

**Comment by yoavweiss** [comment]
@toddreifsteck - The main user for this change is the [Screen Orientation change](https://www.w3.org/TR/screen-orientation/#Screen-orientation-change) algorithm, which seems to be using the sync hook to register async actions. Maybe we can trigger the hook async to begin with?

@mounirlamouri - thoughts?

**Comment by mounirlamouri** [comment]
Running the hooks sync has the benefit of allowing sync hooks if needed and in practice avoid issues of re-entrency.

**Comment by toddreifsteck** [comment]
Now that I've read the consumer specification, I think the Screen orientation spec could be improved by altering the animation frame tasks to be a step during render steps that checks visibility and executes at that point. As written, if a state change from visible to not visible occurs, that will cause 2 sets of steps to run which seems suboptimal. If re-written that way, I don't believe a new hook is needed in Page Visibility.

@mounirlamouri What do you think?

**Comment by toddreifsteck** [comment]
Said another way.. each animation step needs to check 2 things: 1. Did the orientation change from last time? If so, fire that subset of steps. 2. Did the tracked state of visibility change from false to true? If so, run the visibility transition from false to true set of steps. (If the visibility flipped from false to true to false within a frame before the animation steps, I don't think we want the animation steps to execute the transition.)

Does what I'm saying make sense?

**Comment by mounirlamouri** [comment]
I don't think we should optimise the number of steps. Hooking into the animation steps would have us run a check on every frame which I doubt any UA would implement. Unless I misunderstood?

**Comment by toddreifsteck** [comment]
K, understood. I'm signing off and merging this. I feel it would be "cleaner" to add a call from Page Visibility to invoke Screen Orientation but I don't have a reason to block the "register/execute" spec design. :-)

I've also added an issue to Screen Orientation to track what seems to be a processing model issue. https://github.com/w3c/screen-orientation/issues/179  Thanks!

**Comment by rakuco** [comment]
Were these definitions intentionally not exported with `data-export`? I can't seem to be able to reference them in other specs.

**Comment by marcoscaceres** [comment]
The latest published version on TR has them as exported, but they have not been picked up yet by WebRef for some reason. 

I'll see if I can find out why.

**Comment by marcoscaceres** [comment]
@rakuco, filed https://github.com/w3c/respec-web-services/issues/200 ... will try to fix it there.

**Comment by rakuco** [comment]
> Were these definitions intentionally not exported with `data-export`? I can't seem to be able to reference them in other specs.

For future reference: Marcos exported one of the definitions in 730b632aa6dc228bac15d34c65e38aa58e1bf707, and I'm fixing the other in #72.

**Pull request merged**
