### PR TITLE
visibility-aware video playback example

### LINKED ISSUE #10: Examples are a bit far-fetched
The examples in the spec, in indeed the stated motivation for this spec (the development of power and CPU efficient web applications), is a bit far-fetched as currently presented. In particular, the examples  using `setTimeout()` would only yield marginal power savings - turning on the phone radio in the way shown would make @igrigorik cry :) 

The value of the spec is simply in specifying the visibility state of a document in the platform. This primitive then allows other APIs to create more power efficient behavior like "requestAnimationFrame()" or prevent certain things from happening (e.g., preventing rotation changes if the document is hidden). 

I think the spec should be refocused to describe the above (i.e., what it's foundation role is in the web platform).

### PR DESCRIPTION
**Pull request by igrigorik**
Closes #10.

### CODE REVIEW

**Comment by toddreifsteck** [comment]
Much better! Merging

**Comment by marcoscaceres** [comment]
Post merge LGTM. I ran tidy over the document and recommitted.

**Comment by marcoscaceres** [comment]
Actually, I lied. I need to get @plehegar to give me push access.

**Comment by toddreifsteck** [comment]
Marcos, please feel free to do the work in a fork and make a merge commit with cleanup. We'll happily take it!

**Comment by igrigorik** [comment]
@marcoscaceres @toddreifsteck fixed in https://github.com/w3c/page-visibility/commit/876096c784c296641fd854144a955e76dc1c67de.

**Pull request merged**
