### PR TITLE
Editorial: remove note about hidden being 'historical'

### LINKED ISSUE #63: Treating .hidden as "historical" seems unhelpful
Given the `document.hidden` is supported everywhere, and I doubt there are any plans for engines to drop it, I think the spec should stop treating it as "historical".

### PR DESCRIPTION
**Pull request by marcoscaceres**
closes #63

### CODE REVIEW

**Comment by yoavweiss** [comment]
What's the best practice to indicate that some features are ones that developers should not be using, even if we don't have a clear path to deprecate and remove them?

**Comment by marcoscaceres** [comment]
I'd suggest us updating MDN for maximum reach - as most developers will end up there, rather than here... however, we can also mark things up as "best-practice"... but to be honest, specs making "best practice" suggestions is not great. I understand why we might want to encourage developers to use the enums, but still, using `hidden` doesn't seem to have any disadvantages over using the enum value.

**Comment by yoavweiss** [comment]
@igrigorik - thoughts?

**Comment by igrigorik** [comment]
What's the downside of providing guidance both here and in MDN? At the end of the day, the spec is the source of truth, not MDN. /cc @philipwalton for opinions™.

**Comment by marcoscaceres** [comment]
I guess I'm also questioning the validity of the advice: there doesn't seem to be any valid technical or performance or other reason to avoid using `.hidden` (that I can see - but please educate me if there is). 

Given that `.hidden` seems to be non-harmful, and has no side-effects, we should really just leave it to authors to choose which is best for their code.

**Review by npm1 — APPROVED** [review]
FWIW given that we do not intend to extend the set of possible visibility states in the near future I agree with this.

**Pull request merged**
