### PR TITLE
Define onvisibilitychange

### LINKED ISSUE #22: Nothing defines the behaviour of Document::onvisibilitychange

### PR DESCRIPTION
**Pull request by igrigorik**
Closes #22.

### CODE REVIEW

**Comment by Ms2ger** [comment]
lgtm

**Comment by igrigorik** [comment]
@toddreifsteck @plehegar any knits or objections before I merge?

**Comment by plehegar** [comment]
:+1:

**Comment by toddreifsteck** [comment]
@travisleithead Travis, can you confirm this looks good?
(I'm not 100% familiar with EventHandler IDL and will stop by for a quick F2F.)

**Comment by igrigorik** [comment]
Merging. @travisleithead let us know if you see anything missing.

**Pull request merged**
