### PR TITLE
Rewrite of spec

### PR DESCRIPTION
**Pull request by marcoscaceres**
- Added ReSpec support. 
- Fixed cross refs
- Defined algorithms that others can hook into. 
- Defined the visibility states properly. 
- reworked examples
- fixed a bunch of typos (though might have introduced new ones). 
- added support for HTML tidy - so the markup can actually be maintained!
- General improvements all around. 
- added task source.

### CODE REVIEW

**Comment by igrigorik** [comment]
Preview: https://rawgit.com/marcoscaceres/page-visibility/rewrite/index.html
- I like the new structure with VisibilityState enum.
- The "now visible algorithm" seems to be indented one level too deep?
- Q: how do I hook into these algorithms?

Overall, this is looking great!

**Comment by marcoscaceres** [comment]
> The "now visible algorithm" seems to be indented one level too deep?

Ah woops. Fixing. 

> Q: how do I hook into these algorithms?

One just reference them by name and links to them.

**Comment by marcoscaceres** [comment]
Updated PR, fixing the "now visible algorithm" indentation level.

**Comment by igrigorik** [comment]
Did another pass, don't have any other knits -- lgtm. That said, I'd be nice to get a few more pairs of eyes on this before we merge, since its a substantial rewrite. 

/cc @toddreifsteck @plehegar

**Comment by marcoscaceres** [comment]
Agree, it would be good to get a few more eyes on it. I did my best to avoid changing anything normative or algorithmic. I mostly just rearranged the content and removed redundant assertions.

**Comment by plehegar** [comment]
I'll look at it this afternoon. Thank you @marcoscaceres in any case.

**Comment by plehegar** [comment]
btw, if we all agree the rewrite is a good one, I'd like to propose that we publish as a third edition of the PV REC. Since it doesn't make normative changes, it ought to be pretty easy to do so imho and we don't have any substantive change waiting anyway. Marcos, suggestions are welcome on how you'd like to get credited in the spec btw. Anything is fine by me as far as I am concerned since you did the work.

**Comment by tobint** [comment]
I looked it over fairly quickly and it looks good to me. Formatting looks stellar. Text seems clear. Nothing jumped out in normative text as concerning. But those are my two cents. I would wait to hear back from @toddreifsteck as he is checking with a few others on the team who are interested to see if they have feedback.

**Comment by plehegar** [comment]
LGTM

**Comment by yoavweiss** [comment]
Looks good! :)
A couple of nits:
- There's a bug in example 2 - pages changing visibility often will never get synced.
- The "editors" section needs updating :)

**Comment by yoavweiss** [comment]
It's probably also worth while to add a note stating why a separate `hidden` attribute is required when its state is identical to `visibilityState==hidden`

**Comment by toddreifsteck** [comment]
LGTM

@yoavweiss , are you ok with moving your feedback into new issues or would you prefer them resolved before we take this?

**Comment by yoavweiss** [comment]
Yeah, I'm cool with moving them to separate issues

**Pull request merged**
