### PR TITLE
Allow a user agent to return hidden when obscured

### PR DESCRIPTION
**Pull request by toddreifsteck**
https://github.com/w3c/page-visibility/issues/34

***
<a href="https://pr-preview.s3.amazonaws.com/toddreifsteck/page-visibility/pull/46.html" title="Last updated on Sep 17, 2019, 7:32 AM UTC (1f1c068)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/page-visibility/46/f663421...toddreifsteck:1f1c068.html" title="Last updated on Sep 17, 2019, 7:32 AM UTC (1f1c068)">Diff</a>

### CODE REVIEW

**Comment by yoavweiss** [comment]
@toddreifsteck - can you resolve the conflicts?

**Comment by siusin** [comment]
@yoavweiss @toddreifsteck 
Conflicts resolved.

**Comment by toddreifsteck** [comment]
@rniwa Please check this PR for feedback originally submitted on #45. I made a mistake in my repo and am choosing to submit both as 1 PR.

**Review by rniwa — APPROVED** [review]
Sorry for the delay. This looks good to me.

**Pull request merged**
